[project]
name = "igc-lib"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "pathlib2>=2.1.0",
    "simplekml>=1.3.1",
]

[dependency-groups]
dev = [
    "folium>=0.20.0",
    "jupyterlab>=4.5.2",
    "matplotlib>=3.10.8",
]
